#!/bin/bash

python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 1 > output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 2 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 3 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 4 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 5 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 6 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 7 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 8 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 9 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 10 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 11 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 12 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 13 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 14 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 15 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 16 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 17 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 18 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 19 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 20 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 21 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 22 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 23 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 24 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 25 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 26 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 27 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 28 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 29 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 30 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 31 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 32 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 33 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 34 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 35 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 36 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 37 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 38 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 39 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 40 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 41 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 42 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 43 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 44 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 45 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 46 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 47 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 48 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 49 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 50 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 51 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 52 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 53 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 54 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 55 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 56 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 57 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 58 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 59 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 60 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 61 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 62 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 63 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 64 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 65 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 66 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 67 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 68 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 69 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 70 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 71 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 72 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 73 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 74 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 75 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 76 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 77 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 78 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 79 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 80 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 81 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 82 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 83 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 84 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 85 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 86 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 87 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 88 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 89 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 90 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 91 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 92 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 93 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 94 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 95 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 96 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 97 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 98 >> output/validationCategoryTweets.txt
python src/documentClassifier.py random data/twitterData/categories_tweets.csv 1 99 >> output/validationCategoryTweets.txt